Vagrant.configure("2") do |config|

	config.vm.define "thhusserS" do |centos1|
	  centos1.vm.box = "centos/7"
	  centos1.vm.hostname = "thhusserS"
	  centos1.vm.network "private_network", ip: "192.168.56.110"

	# Définir le fournisseur comme VirtualBox
	  centos1.vm.provider "virtualbox" do |v|
		v.memory = 512  # Mémoire en Mo
		v.cpus = 1  # Nombre de CPU
		v.name = "Server"
	  end
	
	# Activer la connexion SSH sans mot de passe
	  centos1.ssh.insert_key = false
	end
  
	config.vm.define "thhusserSW" do |centos2|
	  centos2.vm.box = "centos/7"
	  centos2.vm.hostname = "thhusserSW"
	  centos2.vm.network "private_network", ip: "192.168.56.111"
  
	  centos2.vm.provider "virtualbox" do |v|
		v.memory = 512
		v.cpus = 1
		v.name = "ServerWorker"
	  end
	
	  centos2.ssh.insert_key = false
	end
  
  end
  