# -*- mode: ruby -*- 

# vi: set ft=ruby : 

  

Vagrant.configure("2") do |config| 

  config.vm.box = "debian/stretch64" 

  config.vm.hostname = "Ma-VM-debian" 

  config.vm.network :private_network, ip: "172.16.16.90" 

  config.vm.provider :virtualbox do |v| 

    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"] 

    v.customize ["modifyvm", :id, "--memory", 1024] 

    v.customize ["modifyvm", :id, "--name", "Ma-VM-debian"] 

    v.customize ["modifyvm", :id, "--cpus", "1"] 

  end 

  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
    service ssh restart 
  SHELL

end